---
listen_on: 127.0.0.1:9753
worlds_path: /var/lib/minecraft/worlds
current_world_name: current_world
server_socket_path: /run/minecraft/minecraft.socket
users_file_path: /var/lib/minecraft/users.yml
base_url: http://127.0.0.1:9753/
min_password_length: 10
max_password_length: 128
